-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CollabPads/maintenance/db/collabpad_revision.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/collabpad_revision (
  sr_rev_id INT UNSIGNED NOT NULL,
  sr_session_id INT UNSIGNED NOT NULL,
  sr_page_title VARBINARY(255) DEFAULT 'null',
  sr_page_namespace INT DEFAULT 0,
  sr_owner VARBINARY(255) DEFAULT 'null',
  sr_rev_actor INT UNSIGNED DEFAULT null,
  sr_participants BLOB NOT NULL,
  PRIMARY KEY(sr_rev_id)
) /*$wgDBTableOptions*/;
