-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/CollabPads/maintenance/db/collabpad_session_page_namespace_page_title_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE INDEX collabpad_session_page_namespace_page_title_index ON /*_*/collabpad_session (s_page_namespace, s_page_title);
