services:
  collabpads-websocket:
    image: hallowelt/collabpads-backend:1.0
    ports:
      - "${COLLABPADS_BACKEND_PORT}:${COLLABPADS_BACKEND_PORT}"
    environment:
      COLLABPADS_BACKEND_PORT: ${COLLABPADS_BACKEND_PORT}
      COLLABPADS_BACKEND_WIKI_BASEURL: ${COLLABPADS_BACKEND_WIKI_BASEURL}
      COLLABPADS_BACKEND_MONGO_DB_HOST: ${COLLABPADS_BACKEND_MONGO_DB_HOST}
      COLLABPADS_BACKEND_MONGO_DB_PORT: ${COLLABPADS_BACKEND_MONGO_DB_PORT}
      COLLABPADS_BACKEND_MONGO_DB_NAME: ${COLLABPADS_BACKEND_MONGO_DB_NAME}
      COLLABPADS_BACKEND_MONGO_DB_USER: ${COLLABPADS_BACKEND_MONGO_DB_USER}
      COLLABPADS_BACKEND_MONGO_DB_PASSWORD: ${COLLABPADS_BACKEND_MONGO_DB_PASSWORD}
      COLLABPADS_BACKEND_LOG_LEVEL: ${COLLABPADS_BACKEND_LOG_LEVEL}
      COLLABPADS_BACKEND_HTTP_CLIENT_OPTIONS: ${COLLABPADS_BACKEND_HTTP_CLIENT_OPTIONS}
      COLLBAPADS_BACKEND_BEHAVIOUR_ON_ERROR: ${COLLBAPADS_BACKEND_BEHAVIOUR_ON_ERROR}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  collabpads-database:
    image: mongo:4.4-focal
    volumes:
      - ./mongo:/data/db
#  mongo-express:
#    image: mongo-express:latest
#    environment:
#      ME_CONFIG_MONGODB_SERVER: collabpads-database
#    ports:
#      - 8091:8081
