-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CollabPads/maintenance/db/sql/collabpad_session.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/collabpad_session (
  s_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  s_page_title VARBINARY(255) DEFAULT 'null',
  s_page_namespace INT DEFAULT 0,
  s_owner VARBINARY(255) DEFAULT 'null',
  s_participants BLOB NOT NULL,
  PRIMARY KEY(s_id)
) /*$wgDBTableOptions*/;
