-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CollabPads/maintenance/db/sql/collabpad_acl_token.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/collabpad_acl_token (
  cat_user_id INT UNSIGNED NOT NULL,
  cat_prefixed_page_title VARBINARY(255) NOT NULL,
  cat_token VARBINARY(32) NOT NULL,
  PRIMARY KEY(
    cat_user_id, cat_prefixed_page_title
  )
) /*$wgDBTableOptions*/;
