-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CollabPads/maintenance/db/collabpad_session.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE collabpad_session (
  s_id SERIAL NOT NULL,
  s_page_title TEXT DEFAULT 'null',
  s_page_namespace INT DEFAULT 0,
  s_owner TEXT DEFAULT 'null',
  s_participants TEXT NOT NULL,
  PRIMARY KEY(s_id)
);
