-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CollabPads/maintenance/db/collabpad_session.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/collabpad_session (
  s_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  s_page_title BLOB DEFAULT 'null',
  s_page_namespace INTEGER DEFAULT 0,
  s_owner BLOB DEFAULT 'null', s_participants BLOB NOT NULL
);
