-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/CollabPads/maintenance/db/collabpad_session_page_namespace_page_title_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__collabpad_session AS
SELECT
  s_id,
  s_page_title,
  s_page_namespace,
  s_owner,
  s_participants
FROM /*_*/collabpad_session;
DROP TABLE /*_*/collabpad_session;


CREATE TABLE /*_*/collabpad_session (
    s_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    s_page_title BLOB DEFAULT 'null',
    s_page_namespace INTEGER DEFAULT 0,
    s_owner BLOB DEFAULT 'null', s_participants BLOB NOT NULL
  );
INSERT INTO /*_*/collabpad_session (
    s_id, s_page_title, s_page_namespace,
    s_owner, s_participants
  )
SELECT
  s_id,
  s_page_title,
  s_page_namespace,
  s_owner,
  s_participants
FROM
  /*_*/__temp__collabpad_session;
DROP TABLE /*_*/__temp__collabpad_session;

CREATE INDEX collabpad_session_page_namespace_page_title_index ON /*_*/collabpad_session (s_page_namespace, s_page_title);
