-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CollabPads/maintenance/db/collabpad_acl_token.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/collabpad_acl_token (
  cat_user_id INTEGER UNSIGNED NOT NULL,
  cat_prefixed_page_title BLOB NOT NULL,
  cat_token BLOB NOT NULL,
  PRIMARY KEY(
    cat_user_id, cat_prefixed_page_title
  )
);
